# Generated by Django 5.0.1 on 2024-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('link', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('proc', models.TextField()),
                ('show', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
    ]
