# Generated by Django 5.0.1 on 2024-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lab',
            field=models.CharField(default=12, max_length=80),
            preserve_default=False,
        ),
    ]
