# Generated by Django 5.0.1 on 2024-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='proc',
            field=models.CharField(max_length=800),
        ),
    ]
