# Generated by Django 5.0.1 on 2024-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_post_proc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='proc',
            field=models.TextField(),
        ),
    ]
