# Generated by Django 5.0.1 on 2024-03-06 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_posting_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
