# Generated by Django 5.0.1 on 2024-03-06 01:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_posting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='proc',
            field=tinymce.models.HTMLField(),
        ),
    ]
